### ISSUE TITLE
Filipino language

### ISSUE THREAD

**Issue by Luklek** [firemaples/microsoft-translator-java-api#2]
Hello, could you maybe add support for Filipino language?
Thanks

**Comment by firemaples** [comment]
OK, I'll add the missed languages in these days

**Comment by Luklek** [comment]
Thanks a lot!

**Comment by firemaples** [comment]
@Luklek 
I've updated the library to version 0.8.5 for completing all missed languages.

**Comment by firemaples** [comment]
587afcb9112e510983671f0ba2c09435a98615b5
