### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by JackPGreen** [firemaples/microsoft-translator-java-api#3]
According to Microsoft's website, their translation tool can use either HTTP or HTTPS to accept requests

https://www.microsoft.com/en-us/translator/faq.aspx (under "Is my data private and secure?").

Are you able to update the library to use the HTTPS versions instead?

The fields are private static final so I am not able to modify them myself using reflection, and am struggling to build the project to edit it directly.

**Comment by firemaples** [comment]
OK, I'll add SSL support in this days.

**Comment by firemaples** [comment]
669e21b0542bc021fa0242d440ab253bca26c0b5

**Comment by firemaples** [comment]
@JackPGreen 
 
Please upgrade to version 0.8.6 then you can use SSL by following code before you trying to tranlate:
```
Translate.setUsingSSL(true);
```
or
```
MicrosoftTranslatorAPI.setUsingSSL(true);
```

**Comment by JackPGreen** [comment]
Thankyou, just tested it :)
