### ISSUE TITLE
V3 API Support

### ISSUE THREAD

**Issue by JackPGreen** [firemaples/microsoft-translator-java-api#4]
As of April 30th, 2019 V2 of the API will be retired and V3 will be the only option.

The interface is significantly different - all requests are sent in JSON (not via URL paramaters) and the responses are different, too.

Please can the library be updated to support this.

**Comment by firemaples** [comment]
Ok, I'll try to update the library to support v3

**Comment by tholu** [comment]
@firemaples Any progress on this?

**Comment by rolandort** [comment]
@firemaples I appreciate your effort to update the library and migrate it to v3 very much! Could you please let us know about the status? And progress? thx

**Comment by firemaples** [comment]
I'm so sorry that my work is busy in these weeks, I'll update this library at the weekend.

**Comment by firemaples** [comment]
I have upgraded the library to 0.8.7 to support API V3, please check.

**Comment by tholu** [comment]
@firemaples Thank you for your work! I'll let you know if I run into any troubles.

**Comment by rolandort** [comment]
My tests using v0.8.7 have been successful so far. Looks good - thanks!

**Comment by zfc0812** [comment]
@dumboxp @tholu @JackPGreen @firemaples 
v0.8.7 is working for debug build but not working for release build. Do you guys experience the same problem?
https://github.com/firemaples/microsoft-translator-java-api/issues/6
