### ISSUE TITLE
v0.8.7 not working for release build

### ISSUE THREAD

**Issue by zfc0812** [firemaples/microsoft-translator-java-api#6]
v0.8.7 is working fine for debug build, however it is not the case for release build. I got this error:

```
java.io.FileNotFoundException: https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&from=ms&to=zh-Hans
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
```
How to fix this?

**Comment by zfc0812** [comment]
I finally knew the cause of this issue, ie proguard. If I disable the proguard, the library is working fine. What exception I should add in proguard rule?

**Comment by firemaples** [comment]
Can the version 0.8.6 work normally with the release version in your application/library?

**Comment by firemaples** [comment]
I'll check the proguard in this days, but I found a bug in the library, just like you said in #1, when Microsoft translator API response a http error(e.g. 403 for out of usage), it will show a error same as you report in #1 and here.

**Comment by firemaples** [comment]
Hi, @zfc0812 
I've tested the library with the proguard config enabled and not reproduce the error that you found.
I update the library to version 0.8.8.1 to retrieve the error message into the exception to determine what happened, please try again with version 0.8.8.1 and read the error message from the exception that produced.

**Comment by zfc0812** [comment]
@firemaples , thanks for the reply but I've solved the problem by adding this proguard rule:
`-keep class io.github.firemaples.** { *; }`
